### ISSUE TITLE
Workbench.rolltimeTo applies local timezone

### ISSUE THREAD

**Issue by mkalinin** [ether-camp/ethereum-testing-reference#12]
hello @kobigurk,
As I understand `Workbench.rolltimeTo` should use `UTC+00` timezone. According to tries with my local env it uses local timezone instead

**Comment by kobigurk** [comment]
Hi,

Indeed, it defaults to local timezone. You have to be explicit for UTC+00.

**Comment by mkalinin** [comment]
got it, thanks!
